### ISSUE TITLE
Pop-up spam with older log files

### ISSUE THREAD

**Issue by willtoth** [orangelight/DSLOG-Reader#1]
The popup *ERROR: dsevent version not supported* runs for each log file creating a pop-up spam tree as soon as the app is opened, and becomes worse if the log files are scrolled. 
![image](https://cloud.githubusercontent.com/assets/8404869/23131556/115bac0c-f750-11e6-90e6-891603ea1e2e.png)

**Comment by orangelight** [comment]
Can you send me a zip of your log files?

**Comment by orangelight** [comment]
This should now be fixed in https://github.com/orangelight/DSLOG-Reader/commit/1b3ebf42b7d4382c4ece992392af8544d7901d6e, thanks for reporting it.
