### ISSUE TITLE
New file location for 2024

### ISSUE THREAD

**Issue by Ardusa** [orangelight/DSLOG-Reader#10]
Looks like the path for logs changed for 2024. Driver Station now puts the logs in the `DSLogs` subdir within the old path. The file format is compatible, though.
![image](https://github.com/orangelight/DSLOG-Reader/assets/75839690/c76fc707-f804-4518-a065-9607a2eeaf28)

**Comment by orangelight** [comment]
Fixed with Version 2.3.0 https://github.com/orangelight/DSLOG-Reader/releases
