### ISSUE TITLE
Log file render error

### ISSUE THREAD

**Issue by jcorcoran** [orangelight/DSLOG-Reader#8]
I have a log file from a match today that looks pretty special.

In DSLog Reader 2.2:
![image](https://user-images.githubusercontent.com/1295877/159135393-1a35d754-a6c6-4189-998d-1313c4fae5a4.png)

In Driverstation log viewer:
![image](https://user-images.githubusercontent.com/1295877/159135411-a1c11902-5c7f-410a-9d04-a87965f84da6.png)

Am I just doing something wrong?

Log file here for reference : 
[2022_03_19 12_55_56 Sat.zip](https://github.com/orangelight/DSLOG-Reader/files/8309951/2022_03_19.12_55_56.Sat.zip)

**Comment by orangelight** [comment]
Not doing anything wrong, looks like I messed up some of the dslog parsing. What PDP/PDH are you using?

**Comment by orangelight** [comment]
I found the issue, it looks like the I assumed that the the first log entry would contain the PDP/PDH type but it does not. I will get a fix out for it soon.

**Comment by orangelight** [comment]
This release https://github.com/orangelight/DSLOG-Reader/releases/tag/v2.2.3 should fix this issue. Thanks for reporting it!

**Comment by jcorcoran** [comment]
Awesome thank you for the new release!

Sorry for delayed response, we are using the REV PDH in case it's still useful info
