### ISSUE TITLE
Microsoft Windows Defender identifies it as virus

### ISSUE THREAD

**Issue by cghercoias** [orangelight/DSLOG-Reader#9]
Virus detected in latest DSLOG-Reader.2.2.exe

![image](https://user-images.githubusercontent.com/8409018/228319606-fcbd812d-582d-43a5-be55-d3f8edd4b45d.png)

Do you guys know what's happening?

**Comment by orangelight** [comment]
I can assure it is not a Trojan, you can look at the code if you would like. To remove the warning I would need to sign the program with a trusted certificate which costs money, as I don't make any money on this project so that will not happen.
